travis:
  secure:
    BINSTAR_TOKEN: 1+DDJaoKzC3/Iq3fT/gqeO/oPbSXt7ZNQMw1JRzONnAeyWC2tFQksAOJuV/Ofe0TlzbcKcCvCMDprUVLUJPHYpShNpaeq/GJ+vJsOBGYAW5AAeGWa4IPBP320R9LQt+87/wAlde5qiohVGLr7kBcGbFAk6SyHEmEvw9hLl5+T4fFFsTxFaoSTGXu6iMM1bsGChKVn0cRSFjmjuwGoNYt6YtHrKDeh/DU4RatHsDbfIz6gk8KyiGJsewZ4wgYOKVhepvlOYJc6r0hdQ4pcWMJU0eo3z1+IGB7scmFN54ycm9rQs7a/DP1RdLeaKjKoiFAP5QytG6pdtXuGYgctMOCP/Ga0XkdxT0dI2BBcygheFwT7VcAjLQ3kxjeHNQyyvNFMaOY8eWHLmoRGCv9Tsl1zQBHBIMkFCUzRuv+rbh+NqKyUjcdc7732fvvJ4pLr8ErgIF6O6BZ4XZhNyY9ZjebAvk6Klb8kCxWh/7OPV1ffVVx7xA2kxNhPJUA+neqYuhDDI25ZBDr9IjFzMPZt996IsHW7d5rQGe9ulhrkwC7lRUtozSNfxW6DQQ2bE348kIHA9slolLExaIIwzChU/qQUXJAUZdo2plx1tmRh3sh2Zna8rR/bgxFR02C8aFuaAiGPWpR2QaCy2JpJCjgw0rHHtdL8HVtGO26HcdOduwDRO4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
